package com.alejandro.ana.notas;

public enum Notas {
/*
* NOTAS: PIESAS EN TRABAJO
* 1) SE CREO UNA CLASE DE RESPONSE PARA LA ARQUITECTURA CON VALIDACION Y CAPA POJO
* FALTA INCORPORAR AL CONTROLLER CAPA POJO EL RESPONSE ENTITY Y HACERLO MAS DINAMICO
*
* 2) HAY OTRO TEMA QUE ES INCORPORAR LAS CLASES DE SEGURIDAD
* 3) INCORPORAR UNA CLASE DE EMAIL PARA ENVIOS  NOTAS: ver el proyecto que me enviaron de email para ver como cargar adjuntos.
* 4) INCORPORAR UNA CLASE DE EMVIOS HTTP
* 5) VER COMO HACER EL SERVICIO HTTPS CON SPRING BOOT QUE EMPESE Y NO TERMINE
* 6) INCORPORAR UNA CLASE DE EXCEL AL PROYECTO
*
* 7) INCORPORAR HERRAMIENTAS O CLASER PARA CREAR ARCHIVOS
* 8) INCORPORAR CLASES DE CARGA Y DESCARGA DE ARCHIVOS
* 9)
*
* 10 ) sacar la estadisticas de horas de trabjo.
*
*
*
* */






}
